### ISSUE TITLE
[Feature Request] Appear on top  

### ISSUE THREAD

**Issue by Terkyz** [yamin8000/freeDictionaryApp#197]
I usually use Librera to read books, and Translate You (an open source translation app) have this amazing feature which you can highlight a word and press the app icon and then the app will appear on top and translate the app without needing to open the full app, it would be very useful to freeDictionaryApp to also have this feature, so I can easily know what something mean.

![TranslateYouAON](https://github.com/user-attachments/assets/570afd9b-ffb3-4ec5-b5c8-0ccb964d3b92)

**Comment by yamin8000** [comment]
@Terkyz As @nvllz said, that feature already exists.  
![Screenshot_2024-11-21-15-34-38-968_io.github.yamin8000.owl.jpg](https://github.com/user-attachments/assets/6221c32c-b826-4d07-97b1-989eab4074ea)

![Screenshot_2024-11-21-15-34-55-799_com.foobnix.pdf.reader.jpg](https://github.com/user-attachments/assets/42698a1a-4e69-4cf2-97e9-819e33d1f981)

![Screenshot_2024-11-21-15-34-52-134_com.foobnix.pdf.reader.jpg](https://github.com/user-attachments/assets/756539cb-7945-4e0c-8892-04770c9c56b9)

You probably need to add it to the list for Librera because by default it may not be there.

**Comment by yamin8000** [comment]
#137 duplicate
