### ISSUE TITLE
Clicking on the dice crashes the app.

### ISSUE THREAD

**Issue by Thyname** [yamin8000/freeDictionaryApp#52]
Version 1.5.5 from f-droid
Samsung m23
Android 13

**Comment by yamin8000** [comment]
> Version 1.5.5 from f-droid Samsung m23 Android 13

Thank you for your report.  
One use case is when there are no words saved in the app database because random words are retrieved from the list of saved words from the body of previous searches. If this is the cause of the bug, this will only happen during the first run or any time the app data is cleared.  
I fixed the problem then reinstalled the app and ensured the app data was cleared (somehow on some Android devices data is restored even after uninstalling and then installing).  
I think the problem is fixed and I'm going to release a new version, feel free to test it if you have the time.  
https://github.com/yamin8000/freeDictionaryApp/releases/tag/1.5.6

**Comment by Thyname** [comment]
Thank you. Yes, I have just installed the app today.
If the fix will come next version then I may wait for the update and give feedback.

**Comment by yamin8000** [comment]
> Thank you. Yes, I have just installed the app today. If the fix will come next version then I may wait for the update and give feedback.

You can use the apk in the Github releases, F-Droid updates are out of my control.
